const catalog = [
    {
        id: 0,
        link: "/",
        img: "/img/content/smart-chasy-huawei-watch-gt-classic-22011108568480_small4.jpg",
        alt: "Смарт часы",
        description: "Смарт-часы HUAWEI Watch GT Classic",
        price: "7584",
        priceSumBasket: 7584,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 1},
        typeProduct: 1
    },
    {
        id: 1,
        link: "/",
        img: "/img/content/14526064820256_small4.jpeg",
        alt: "Детские Водонепроницаемые",
        description: "Детские Водонепроницаемые Умные Часы с gps Smart baby",
        price: "999",
        priceSumBasket: 999,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 9},
        typeProduct: 2
    },
    {
        id: 2,
        link: "/",
        img: "/img/content/20253397472557_small4.jpeg",
        alt: "Электросамокат",
        description: "Смарт-часы XIAOMI Amazfit Verge Blue",
        price: "3599",
        priceSumBasket: 3599,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 8},
        typeProduct: 1
    },
    {
        id: 3,
        link: "/",
        img: "/img/content/48272048070578_small4.jpeg",
        alt: "Смарт-часы",
        description: "Смарт-часы GARMIN Forerunner 235",
        price: "7584",
        priceSumBasket: 7584,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 2},
        typeProduct: 1
    },
    {
        id: 4,
        link: "/",
        img: "/img/content/62428467162146_small4.jpeg",
        alt: "Samsung Galaxy",
        description: "Смарт-часы Samsung Galaxy Watch 46мм Silver",
        price: "9499",
        priceSumBasket: 9499,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 0},
        typeProduct: 1
    },
    {
        id: 5,
        link: "/",
        img: "/img/content/68354208744341_small4.jpeg",
        alt: "Смарт-часы",
        description: "Смарт-часы SAMSUNG Galaxy Watch Active 2 40mm",
        price: "8999",
        priceSumBasket: 8999,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 0},
        typeProduct: 0
    },
    {
        id: 6,
        link: "/",
        img: "/img/content/86840362163261_small4.jpeg",
        alt: "Смарт-часы ",
        description: "Смарт-часы APPLE Watch Series 4 40mm Gold Aluminium with",
        price: "12999",
        priceSumBasket: 12999,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 3},
        typeProduct: 0
    },
    {
        id: 7,
        link: "/",
        img: "/img/content/36ec8e76800f50abc14643684a5f1624.jpg",
        alt: "Смарт часы",
        description: "Смарт-часы SAMSUNG Galaxy Watch 46mm Silver (SM-R800NZSA)",
        price: "6999",
        priceSumBasket: 6999,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 0},
        typeProduct: 1
    },
    {
        id: 8,
        link: "/",
        img: "/img/content/diesel_diesel-dz1657_-erkek-kol-saati_119269.jpg",
        alt: "Смарт часы",
        description: "Diesel - Часы DZ4318",
        price: "5799",
        priceSumBasket: 5799,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 4},
        typeProduct: 1
    },
    {
        id: 9,
        link: "/",
        img: "/img/content/dz4375_1_.jpg",
        alt: "Смарт часы",
        description: "ЧАСЫ DIESEL DZ4503",
        price: "4644",
        priceSumBasket: 4644,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 4},
        typeProduct: 1
    },
    {
        id: 10,
        link: "/",
        img: "/img/content/large_img_1621229.jpg",
        alt: "Смарт-часы",
        description: "ARMANI EXCHANGE - ЧАСЫ AX2805",
        price: "4199",
        priceSumBasket: 4199,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 7},
        typeProduct: 1
    },
    {
        id: 11,
        link: "/",
        img: "/img/content/pierre_lannier_225d466_images_15903069939.jpg",
        alt: "Смарт-часы",
        description: "Мужские часы PIERRE LANNIER 225D466",
        price: "4798",
        priceSumBasket: 4798,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 0},
        typeProduct: 1
    },
    {
        id: 12,
        link: "/",
        img: "/img/content/8381500_images_1612801495.jpg",
        alt: "Смарт-часы",
        description: "Casio Original G-Shock GA100-1A1ER",
        price: "2828",
        priceSumBasket: 2828,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 5},
        typeProduct: 1
    },
    {
        id: 13,
        link: "/",
        img: "/img/content/66786156357148_small4.jpeg",
        alt: "Браслет",
        description: "Миланский сетчатый ремешок для часов Fitbit Blaze - Black",
        price: "599",
        priceSumBasket: 599,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Хит", classFilter: "hit", val: 0},
        brand: {name: "", val: 6},
        typeProduct: 3
    },
    {
        id: 14,
        link: "/",
        img: "/img/content/66786156357148_small4.jpeg",
        alt: "Браслет",
        description: "Миланский сетчатый ремешок для часов Fitbit Blaze - Silver",
        price: "499",
        priceSumBasket: 499,
        counterBasket: 1,
        idBasket: false,
        buy: "Купить",
        inBasket: "В корзине",
        filterIcon: {name: "Новинка", classFilter: "new", val: 1},
        brand: {name: "", val: 6},
        typeProduct: 3
    },
]

export {
    catalog
}